### ISSUE TITLE
Getting an Error !!

### ISSUE THREAD

**Issue by ashar799** [SheffieldML/vargplvm#4]
Hi,
I tried to use the VGPLVM code with the standard settings 
options <-  vargplvmOptions('dtcvar')
## Y is n times D matrix (D= 20)(N=100)

model <- vargplvmCreate(5, D, Y, options)
model <-  vargplvmParamInit(model, model$m, model$X)
model <- vargplvmOptimise(model, display =1, iters = 100)

I get the following error on optimization:
Error in 2 \* partInd2 : non-numeric argument to binary operator

Can somebody pls help!!!

**Comment by adamian** [comment]
Hi,
Are you using the R package? I think it may be unsupported by now..
You might want to try the MATLAB version (or the Python one which you can find in GPy).

**Comment by ashar799** [comment]
Thanks for the information!
